name: CSV Transformation

on:
  push:
    branches:
      - main
    paths:
      - 'CSV/**'  # Matches any CSV file in the CSV folder

  workflow_dispatch:  # Allows manual trigger from GitHub Actions tab

permissions:
  contents: write  # Grants permission for GitHub Actions to push changes

jobs:
  transform_csv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      - name: Download CSV files dynamically
        run: |
          mkdir -p data
          curl -s https://api.github.com/repos/${{ github.repository }}/contents/CSV | jq -r '.[].download_url' | grep ".csv" | while read url; do curl -o "data/$(basename $url)" $url; done

      - name: Run transformation script
        run: python transform_csv.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"
          git add transformed_file.csv
          git commit -m "Auto-update transformed CSV" || echo "No changes to commit"
          git push
